Add check to ensure only running once on host

diff --git a/arch-upgrade b/arch-upgrade
--- a/arch-upgrade
+++ b/arch-upgrade
@@ -103,6 +103,12 @@ fi
 tmp=$(mktemp)
 trap "rm -f $tmp; exit" 0 1 2 3 15
 
+exec 200>"/tmp/$PROG"
+if ! flock -n 200; then
+    echo "ERROR: $PROG is already running!" >&2
+    exit 1
+fi
+
 echo "##### Arch software upgrade starting #####"
 
 if [[ $CMDLINE -ne 0 ]]; then
