Check and report if html2text not installed

diff --git a/arch-upgrade b/arch-upgrade
--- a/arch-upgrade
+++ b/arch-upgrade
@@ -93,6 +93,10 @@ fi
 
 # Grab latest news and report any new news items
 if [ $NEWS -ne 0 ]; then
+    if ! which html2text &>/dev/null; then
+	echo "ERROR: Please install html2text utility." >&2
+	exit 1
+    fi
     curl -silent "$NEWSURL" |
     html2text --ignore-emphasis --ignore-links --ignore-images |
     grep '^20[0-9][0-9]-' | head -$NUMNEWS >$tmp
